# Generated by Django 6.0.4 on 2026-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('from_location', models.CharField(db_index=True, max_length=100)),
                ('to_location', models.CharField(db_index=True, max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fare_min', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fare_max', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TimeField(help_text='Scheduled departure time')),
                ('arrival', models.TimeField(help_text='Scheduled arrival time')),
                ('days', models.CharField(default='daily', help_text="'daily', 'weekdays', 'weekends', or comma-separated days: 'mon,wed,fri'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['departure'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(help_text='Stop sequence number')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distance_from_start_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'route_stops',
                'ordering': ['route', 'order'],
            },
        ),
    ]
