# Generated by Django 6.0.4 on 2026-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(blank=True, help_text='For unregistered vehicles not in DB', max_length=20)),
                ('flag_type', models.CharField(choices=[('unregistered', 'Unregistered Vehicle'), ('expired_docs', 'Expired Documents'), ('invalid_route', 'Operating on Unauthorized Route'), ('overloading', 'Passenger Overloading'), ('other', 'Other Violation')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Police')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTOAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rto_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('driver', 'Driver'), ('document', 'Document')], db_index=True, max_length=10)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Inspection')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection/flagging')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
