# Generated by Django 6.0.4 on 2026-04-09 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rto', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceflag',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceflag',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_flags', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='rtoauditlog',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationrecord',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationrecord',
            name='rto_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'rto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='vehicles.vehicle'),
        ),
    ]
