# Generated by Django 6.0.4 on 2026-04-09 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bus_code', models.CharField(blank=True, help_text='Short code shown to users e.g. A01', max_length=10, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Mini Bus'), ('tempo', 'Tempo Traveller'), ('auto', 'Auto Rickshaw')], default='bus', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending RTO Verification'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected by RTO'), ('flagged', 'Flagged (Non-Compliant)')], db_index=True, default='pending', max_length=10)),
                ('rto_verified', models.BooleanField(default=False)),
                ('rto_verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='routes.route')),
                ('rto_verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'rto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_verified_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rc', 'Registration Certificate'), ('insurance', 'Insurance'), ('fitness', 'Fitness Certificate'), ('permit', 'Route Permit'), ('puc', 'Pollution Certificate'), ('tax_token', 'Tax Token')], max_length=15)),
                ('document', models.FileField(upload_to='uploads/vehicle_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'rto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_documents',
                'unique_together': {('vehicle', 'doc_type')},
            },
        ),
    ]
