# Generated by Django 6.0.4 on 2026-04-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('operator', models.CharField(default='BSNL', max_length=50)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('mcc', models.PositiveSmallIntegerField(default=404, help_text='Mobile Country Code')),
                ('mnc', models.PositiveSmallIntegerField(default=1, help_text='Mobile Network Code')),
                ('lac', models.PositiveIntegerField(help_text='Location Area Code')),
                ('cell_id', models.PositiveIntegerField(help_text='Cell ID')),
                ('coverage_radius_m', models.PositiveIntegerField(default=3000)),
                ('signal_strength_dbm', models.IntegerField(default=-80)),
                ('frequency_band', models.CharField(default='900MHz', max_length=10)),
                ('technology', models.CharField(choices=[('2G', '2G GSM'), ('3G', '3G UMTS'), ('4G', '4G LTE')], default='2G', max_length=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cell_towers',
                'unique_together': {('mcc', 'mnc', 'lac', 'cell_id')},
            },
        ),
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_m', models.PositiveIntegerField(default=1200)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bearing_deg', models.DecimalField(decimal_places=2, default=0, help_text='Direction 0–360°', max_digits=5)),
                ('tower1_rssi', models.IntegerField(default=-80, help_text='Signal strength dBm')),
                ('tower2_rssi', models.IntegerField(default=-90)),
                ('tower3_rssi', models.IntegerField(default=-100)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_used', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tower1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.celltower')),
                ('tower2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.celltower')),
                ('tower3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.celltower')),
            ],
            options={
                'db_table': 'vehicle_tracking',
                'ordering': ['-timestamp'],
            },
        ),
    ]
