# Generated by Django 6.0.4 on 2026-04-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletracking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicletracking',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_tra_vehicle_275ebc_idx'),
        ),
    ]
